server:
  port: 5678
spring:
  application:
    name: gctcw-robot
  profiles:
    active: "@springboot.profiles.active@"
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  continue-on-error: false
  druid:
    # 初始化连接数
    initial-size: 3
    # 最小连接数
    min-idle: 3
    # 最大连接数
    max-active: 30
    # 最大等待时间 单位：毫秒
    max-wait: 9000
    # 配置间隔多久进行一次对需要关闭的空闲连接的检测，单位：毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位：毫秒
    min-evictable-idle-time-millis: 300000
    # 检测连接有效性的SQL文
    validation-query: SELECT 1
    # 建议配置为true，不影响性能，并且保证安全性。
    # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，
    # 执行validationQuery检测连接是否有效。
    test-while-idle: true
    # 申请连接时执行validationQuery检测连接是否有效，
    # 做了这个配置会降低性能。
    test-on-borrow: false
    # 归还连接时执行validationQuery检测连接是否有效，
    # 做了这个配置会降低性能
    test-on-return: false
    # 是否缓存preparedStatement，也就是PSCache。
    # PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    pool-prepared-statements: true
    # 要启用PSCache，必须配置大于0，
    # 当大于0时，poolPreparedStatements自动触发修改为true。
    # 在Druid中，不会存在Oracle下PSCache占用内存过多的问题，
    # 可以把这个数值配置大一些，比如说100
    max-pool-prepared-statement-per-connection-size: 30


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.gctcw

logging:
  config: classpath:logback-spring.xml

