#---------------------------------------------------------ReadMe------------------------------------------------------#
#---------------------------------------------------SpringBoot配置文件-------------------------------------------------#
#----------------------------------------           《服务器生成环境》                -----------------------------------#
#---------------------------------------------------------ReadMe------------------------------------------------------#
spring:
  datasource:
    url: jdbc:mysql://154.39.148.71:3306/jys?useAffectedRows=true&useSSL=false&allowMultiQueries=true&autoReconnect=true&characterEncoding=UTF-8&useTimezone=false
    # 数据库用户名
    username: jys
    # 数据库密码 如果不希望密码直接写在配置文件中，可以使用ConfigFilter。
    password: Fyi8s2cNGKxcB45n
