#---------------------------------------------------------ReadMe------------------------------------------------------#
#---------------------------------------------------SpringBoot配置文件-------------------------------------------------#
#----------------------------------------           《服务器测试环境》                -----------------------------------#
#---------------------------------------------------------ReadMe------------------------------------------------------#
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jys_v2?useAffectedRows=true&useSSL=false&allowMultiQueries=true&autoReconnect=true&characterEncoding=UTF-8&useTimezone=false
    # 数据库用户名
    username: jysv2
    # 数据库密码 如果不希望密码直接写在配置文件中，可以使用ConfigFilter。
    password: EaTSjMi5kShpfrAr
